config/routes.rb
Twizilla::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, :only => [:create, :destroy]
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  
  root :to => "pages#home"

  match '/contact', :to => "pages#contact"
  match '/about',   :to => "pages#about"
  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class='round'>
		Copyright &copy <%= link_to 'Vincent Yang', 'http://vinceisme.heroku.com/', :target => '_blank'%>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>	
	<%= link_to logo, root_path %>
	<nav class = 'round'>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
				<li><%= link_to "Profile", user_path(current_user)%></li>
				<li><%= link_to "Users", users_path %></li>
				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<li><%= link_to "Sign Out", signout_path %></li>
			<% else %>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Sign In", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</header> 

app/views/layouts/_stylesheets.html.erb
	<!--[if lt IE 9]>
	<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
	<%= render 'layouts/stylesheets' %>
	<%= csrf_meta_tag %>
</head>
<body>
	<div class="container">	
		<%= render 'layouts/header' %>
		<section class = 'round'>
			<% flash.each do |key, val| %>
				<div class = "flash round <%= key %>"><%= val %></div>
			<% end %>
			<%= yield %> 
		</section>
		<%= render 'layouts/footer'%>
	</div>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>